# VacationPy
----

#### Note
* Keep an eye on your API usage. Use https://developers.google.com/maps/reporting/gmp-reporting as reference for how to monitor your usage and billing.

* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os

# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [37]:
filepath = "../VacationPy/weather_data.csv"

weather_data = pd.read_csv(filepath)
weather_data.head()

,Unnamed: 0,City,Latitude,Longitude,Max Temperature,Humidity,Wind Speed,Cloudiness,Country,Data Receiving Time (GMT)
0,0,nikolskoye,59.70,30.79,44.01,94,8.21,65,RU,1603928398
1,1,pangnirtung,66.15,-65.71,8.94,79,4.65,30,CA,1603928398
2,2,bluff,-46.60,168.33,57.00,77,5.99,100,NZ,1603928399
3,3,clyde river,70.47,-68.59,14.61,89,6.11,96,CA,1603928399
4,4,kapaa,22.08,-159.32,79.00,71,11.32,34,US,1603928399

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [43]:
gmaps.configure(api_key=g_key)

location = weather_data[["Latitude", "Longitude"]].astype(float)

humidity = weather_data['Humidity']
fig = gmaps.figure()
heat_layer = gmaps.heatmap_layer(location, weights=humidity, 
                                 dissipating=False, max_intensity=100,
                                 point_radius = 1.4)
fig.add_layer(heat_layer)
fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [5]:
hotel_df = weather_data.loc[(weather_data['Max Temperature'] < 80) &
                                (weather_data['Max Temperature'] > 70) &
                                (weather_data['Wind Speed'] < 5) &
                                (weather_data['Cloudiness'] == 0) &
                                (weather_data['Humidity'] < 90)]
hotel_df

,Unnamed: 0,City,Latitude,Longitude,Max Temperature,Humidity,Wind Speed,Cloudiness,Country,Data Receiving Time (GMT)
82,82,birao,10.28,22.79,75.31,36,4.38,0,CF,1603928410
116,116,wawa,9.90,4.42,76.73,43,1.68,0,NG,1603928414
257,257,orange,33.70,-117.77,73.99,38,3.00,0,US,1603928292
291,291,pacific grove,36.62,-121.92,73.99,48,4.68,0,US,1603928434
293,293,bosaso,11.28,49.18,76.96,66,3.51,0,SO,1603928435
301,301,coos bay,43.37,-124.22,73.99,10,1.01,0,US,1603928436
321,321,shirgaon,19.70,72.70,77.59,59,4.03,0,IN,1603928438
344,344,ures,29.43,-110.40,79.00,14,1.01,0,MX,1603928441
394,394,mecca,21.43,39.83,72.19,60,2.71,0,SA,1603928447
408,408,jizan,17.33,42.67,76.50,59,1.63,0,SA,1603928448
470,470,giyani,-23.30,30.72,70.99,33,4.36,0,ZA,1603928455
486,486,bilma,18.69,12.92,70.90,19,4.61,0,NE,1603928457
487,487,angoche,-16.23,39.91,74.91,80,1.52,0,MZ,1603928457
507,507,half moon bay,37.46,-122.43,72.00,31,3.00,0,US,1603928459

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [36]:
hotel_df['Hotel Name'] = ""
params = {"radius": 5000,"types": "lodging","language": "en","key": g_key}
    
for index, row in hotel_df.iterrows():
    lat = row["Latitude"]
    lng = row["Longitude"]

    params["location"] = f"{lat},{lng}"
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    
    name_address = requests.get(base_url, params=params)
    name_address = name_address.json()
    try:
        hotel_df.loc[index, "Hotel Name"] = name_address["results"][0]["name"]
    except:
        print("Missing field/result... skipping.")
hotel_df

C:\Users\mclan\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

Missing field/result... skipping.
Missing field/result... skipping.

C:\Users\mclan\anaconda3\envs\PythonData\lib\site-packages\pandas\core\indexing.py:966: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[item] = s

,Unnamed: 0,City,Latitude,Longitude,Max Temperature,Humidity,Wind Speed,Cloudiness,Country,Data Receiving Time (GMT),Hotel Name
82,82,birao,10.28,22.79,75.31,36,4.38,0,CF,1603928410,
116,116,wawa,9.90,4.42,76.73,43,1.68,0,NG,1603928414,
257,257,orange,33.70,-117.77,73.99,38,3.00,0,US,1603928292,La Quinta Inn & Suites by Wyndham Irvine Spectrum
291,291,pacific grove,36.62,-121.92,73.99,48,4.68,0,US,1603928434,Lovers Point Inn
293,293,bosaso,11.28,49.18,76.96,66,3.51,0,SO,1603928435,Red Sea Hotel
301,301,coos bay,43.37,-124.22,73.99,10,1.01,0,US,1603928436,Best Western Holiday Hotel
321,321,shirgaon,19.70,72.70,77.59,59,4.03,0,IN,1603928438,LAXMI GARDEN BEACH RESORT
344,344,ures,29.43,-110.40,79.00,14,1.01,0,MX,1603928441,Hotel HACIENDA San Francisco
394,394,mecca,21.43,39.83,72.19,60,2.71,0,SA,1603928447,Hotel Fairmont Makkah Clock Royal Tower
408,408,jizan,17.33,42.67,76.50,59,1.63,0,SA,1603928448,شهدان. ابوالحجر
470,470,giyani,-23.30,30.72,70.99,33,4.36,0,ZA,1603928455,Kulani Country Lodge
486,486,bilma,18.69,12.92,70.90,19,4.61,0,NE,1603928457,Expeditions Ténére voyages
487,487,angoche,-16.23,39.91,74.91,80,1.52,0,MZ,1603928457,Guest House HESADA
507,507,half moon bay,37.46,-122.43,72.00,31,3.00,0,US,1603928459,"The Ritz-Carlton, Half Moon Bay"

In [20]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Latitude", "Longitude"]]

In [45]:
# Add marker layer ontop of heat map
fig = gmaps.figure()
heat_layer = gmaps.heatmap_layer(location, weights=humidity, 
                                 dissipating=False, max_intensity=100,
                                 point_radius = 1.4)
hotel_layer = gmaps.marker_layer(locations, info_box_content= hotel_info)
fig.add_layer(hotel_layer)
fig.add_layer(heat_layer)
fig
# Display figure

Figure(layout=FigureLayout(height='420px'))