# VacationPy
----

#### Note
* Keep an eye on your API usage. Use https://developers.google.com/maps/reporting/gmp-reporting as reference for how to monitor your usage and billing.

* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os

# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [66]:
filepath = "../VacationPy/weather_data.csv"

city_data = pd.read_csv(filepath)
city_data.head()

,Unnamed: 0,City,Latitude,Longitude,Max Temperature,Humidity,Wind Speed,Cloudiness,Country,Data Receiving Time (GMT)
0,0,nikolskoye,59.70,30.79,44.01,94,8.21,65,RU,1603928398
1,1,pangnirtung,66.15,-65.71,8.94,79,4.65,30,CA,1603928398
2,2,bluff,-46.60,168.33,57.00,77,5.99,100,NZ,1603928399
3,3,clyde river,70.47,-68.59,14.61,89,6.11,96,CA,1603928399
4,4,kapaa,22.08,-159.32,79.00,71,11.32,34,US,1603928399

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [67]:
cd_2 = city_data.dropna(how='any')
gmaps.configure(api_key=g_key)

locations = cd_2[['Latitude', 'Longitude']]
weights = cd_2['Humidity']
fig = gmaps.figure()
fig.add_layer(gmaps.heatmap_layer(locations, weights=weights))
fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [91]:
hotel_df = cd_2.drop(cd_2[(cd_2['Max Temperature'] <= 75) | (cd_2['Max Temperature'] >= 80) | (cd_2['Cloudiness'] >= 50) | (cd_2['Wind Speed'] >= 10)].index)

hotel_df.reset_index(drop=True)

,Unnamed: 0,City,Latitude,Longitude,Max Temperature,Humidity,Wind Speed,Cloudiness,Country,Data Receiving Time (GMT)
0,24,diffa,13.32,12.61,79.57,22,8.68,0,NE,1603928402
1,28,ixtapa,20.70,-105.20,79.75,81,1.99,27,MX,1603928403
2,55,tessalit,20.20,1.01,76.21,18,8.50,0,ML,1603928406
3,77,port antonio,18.18,-76.46,79.00,93,7.00,7,JM,1603928409
4,82,birao,10.28,22.79,75.31,36,4.38,0,CF,1603928410
5,93,salalah,17.02,54.09,78.06,70,2.46,21,OM,1603928411
6,114,mormugao,15.40,73.80,77.86,66,5.68,34,IN,1603928414
7,116,wawa,9.90,4.42,76.73,43,1.68,0,NG,1603928414
8,163,tougan,13.07,-3.07,78.73,16,6.17,0,BF,1603928420
9,197,alacranes,22.77,-81.57,77.11,92,6.76,3,CU,1603928424
10,207,manzanillo,20.34,-77.12,78.35,87,6.51,6,CU,1603928425
11,265,domoni,-12.26,44.53,76.30,78,3.62,15,KM,1603928431
12,287,coachella,33.68,-116.17,79.00,20,7.00,0,US,1603928203
13,293,bosaso,11.28,49.18,76.96,66,3.51,0,SO,1603928435
14,321,shirgaon,19.70,72.70,77.59,59,4.03,0,IN,1603928438
15,344,ures,29.43,-110.40,79.00,14,1.01,0,MX,1603928441
16,358,bandarbeyla,9.49,50.81,77.23,86,3.71,17,SO,1603928443
17,359,bull savanna,17.89,-77.59,77.29,85,5.48,47,JM,1603928443
18,378,port hedland,-20.32,118.57,77.05,74,8.30,0,AU,1603928445
19,408,jizan,17.33,42.67,76.50,59,1.63,0,SA,1603928448
20,430,jardim,-21.48,-56.14,77.05,78,2.26,13,BR,1603928451
21,442,bentiu,9.23,29.83,75.76,69,5.14,0,SS,1603928452
22,450,boyolangu,-8.12,111.89,79.68,78,2.06,25,ID,1603928453
23,489,san lorenzo,-25.33,-57.53,77.63,40,6.96,32,PY,1603928457
24,491,takoradi,4.88,-1.76,77.47,88,7.25,48,GH,1603928458
25,499,mumford,5.26,-0.76,77.77,90,6.96,18,GH,1603928458
26,509,kidal,18.44,1.41,78.46,17,7.36,0,ML,1603928459

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [92]:
hotel_df['Hotel Name'] = ""

params = {
    "radius": 5000,
    "types": "lodging",
    "language": "en",
    "key": g_key
}
    
for index, row in hotel_df.iterrows():
    
    lat = row["Latitude"]
    lng = row["Longitude"]

    params["location"] = f"{lat},{lng}"
    
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    
    name_address = requests.get(base_url, params=params)
    
    name_address = name_address.json()
    
    try:
        hotel_df.loc[index, "Hotel Name"] = name_address["results"][0]["name"]
    except:
        print("Missing field/result... skipping.")
hotel_df

Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.

,Unnamed: 0,City,Latitude,Longitude,Max Temperature,Humidity,Wind Speed,Cloudiness,Country,Data Receiving Time (GMT),Hotel Name
24,24,diffa,13.32,12.61,79.57,22,8.68,0,NE,1603928402,ProDAF/Diffa
28,28,ixtapa,20.70,-105.20,79.75,81,1.99,27,MX,1603928403,Container Inn Puerto Vallarta
55,55,tessalit,20.20,1.01,76.21,18,8.50,0,ML,1603928406,
77,77,port antonio,18.18,-76.46,79.00,93,7.00,7,JM,1603928409,Trident Hotel
82,82,birao,10.28,22.79,75.31,36,4.38,0,CF,1603928410,
93,93,salalah,17.02,54.09,78.06,70,2.46,21,OM,1603928411,HAMDAN PLAZA HOTEL
114,114,mormugao,15.40,73.80,77.86,66,5.68,34,IN,1603928414,Coconut Creek Resort
116,116,wawa,9.90,4.42,76.73,43,1.68,0,NG,1603928414,
163,163,tougan,13.07,-3.07,78.73,16,6.17,0,BF,1603928420,Hôtel SMAK
197,197,alacranes,22.77,-81.57,77.11,92,6.76,3,CU,1603928424,Hotel Union de Reyes
207,207,manzanillo,20.34,-77.12,78.35,87,6.51,6,CU,1603928425,Adrian & Tonia
265,265,domoni,-12.26,44.53,76.30,78,3.62,15,KM,1603928431,Loulou
287,287,coachella,33.68,-116.17,79.00,20,7.00,0,US,1603928203,The Vineyards Luxury Motor Coach RV Resort and...
293,293,bosaso,11.28,49.18,76.96,66,3.51,0,SO,1603928435,Red Sea Hotel
321,321,shirgaon,19.70,72.70,77.59,59,4.03,0,IN,1603928438,LAXMI GARDEN BEACH RESORT
344,344,ures,29.43,-110.40,79.00,14,1.01,0,MX,1603928441,Hotel HACIENDA San Francisco
358,358,bandarbeyla,9.49,50.81,77.23,86,3.71,17,SO,1603928443,REER XOOSHLE GROUP
359,359,bull savanna,17.89,-77.59,77.29,85,5.48,47,JM,1603928443,Big Red's
378,378,port hedland,-20.32,118.57,77.05,74,8.30,0,AU,1603928445,The Esplanade Hotel
408,408,jizan,17.33,42.67,76.50,59,1.63,0,SA,1603928448,شهدان. ابوالحجر
430,430,jardim,-21.48,-56.14,77.05,78,2.26,13,BR,1603928451,Hotel Estância
442,442,bentiu,9.23,29.83,75.76,69,5.14,0,SS,1603928452,Mandela hôtel
450,450,boyolangu,-8.12,111.89,79.68,78,2.06,25,ID,1603928453,Yos ega cv
489,489,san lorenzo,-25.33,-57.53,77.63,40,6.96,32,PY,1603928457,Ámbar Hotel
491,491,takoradi,4.88,-1.76,77.47,88,7.25,48,GH,1603928458,Raybow International Hotel
499,499,mumford,5.26,-0.76,77.77,90,6.96,18,GH,1603928458,Spanish Villa
509,509,kidal,18.44,1.41,78.46,17,7.36,0,ML,1603928459,

In [94]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Latitude", "Longitude"]]

In [95]:
marker_layer = gmaps.marker_layer(locations,info_box_content=hotel_info)
fig.add_layer(marker_layer)

# Display figure
fig

Figure(layout=FigureLayout(height='420px'))